require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmployeeMobilesController do

  # This should return the minimal set of attributes required to create a valid
  # EmployeeMobile. As you add validations to EmployeeMobile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "number" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmployeeMobilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all employee_mobiles as @employee_mobiles" do
      employee_mobile = EmployeeMobile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:employee_mobiles).should eq([employee_mobile])
    end
  end

  describe "GET show" do
    it "assigns the requested config_person as @config_person" do
      employee_mobile = EmployeeMobile.create! valid_attributes
      get :show, {:id => employee_mobile.to_param}, valid_session
      assigns(:config_person).should eq(employee_mobile)
    end
  end

  describe "GET new" do
    it "assigns a new config_person as @config_person" do
      get :new, {}, valid_session
      assigns(:config_person).should be_a_new(EmployeeMobile)
    end
  end

  describe "GET edit" do
    it "assigns the requested config_person as @config_person" do
      employee_mobile = EmployeeMobile.create! valid_attributes
      get :edit, {:id => employee_mobile.to_param}, valid_session
      assigns(:config_person).should eq(employee_mobile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EmployeeMobile" do
        expect {
          post :create, {:config_person => valid_attributes}, valid_session
        }.to change(EmployeeMobile, :count).by(1)
      end

      it "assigns a newly created config_person as @config_person" do
        post :create, {:config_person => valid_attributes}, valid_session
        assigns(:config_person).should be_a(EmployeeMobile)
        assigns(:config_person).should be_persisted
      end

      it "redirects to the created config_person" do
        post :create, {:config_person => valid_attributes}, valid_session
        response.should redirect_to(EmployeeMobile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved config_person as @config_person" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeMobile.any_instance.stub(:save).and_return(false)
        post :create, {:config_person => { "number" => "invalid value" }}, valid_session
        assigns(:config_person).should be_a_new(EmployeeMobile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeMobile.any_instance.stub(:save).and_return(false)
        post :create, {:config_person => { "number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested config_person" do
        employee_mobile = EmployeeMobile.create! valid_attributes
        # Assuming there are no other employee_mobiles in the database, this
        # specifies that the EmployeeMobile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EmployeeMobile.any_instance.should_receive(:update).with({ "number" => "MyString" })
        put :update, {:id => employee_mobile.to_param, :config_person => { "number" => "MyString" }}, valid_session
      end

      it "assigns the requested config_person as @config_person" do
        employee_mobile = EmployeeMobile.create! valid_attributes
        put :update, {:id => employee_mobile.to_param, :config_person => valid_attributes}, valid_session
        assigns(:config_person).should eq(employee_mobile)
      end

      it "redirects to the config_person" do
        employee_mobile = EmployeeMobile.create! valid_attributes
        put :update, {:id => employee_mobile.to_param, :config_person => valid_attributes}, valid_session
        response.should redirect_to(employee_mobile)
      end
    end

    describe "with invalid params" do
      it "assigns the config_person as @config_person" do
        employee_mobile = EmployeeMobile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeMobile.any_instance.stub(:save).and_return(false)
        put :update, {:id => employee_mobile.to_param, :config_person => { "number" => "invalid value" }}, valid_session
        assigns(:config_person).should eq(employee_mobile)
      end

      it "re-renders the 'edit' template" do
        employee_mobile = EmployeeMobile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeMobile.any_instance.stub(:save).and_return(false)
        put :update, {:id => employee_mobile.to_param, :config_person => { "number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested config_person" do
      employee_mobile = EmployeeMobile.create! valid_attributes
      expect {
        delete :destroy, {:id => employee_mobile.to_param}, valid_session
      }.to change(EmployeeMobile, :count).by(-1)
    end

    it "redirects to the employee_mobiles list" do
      employee_mobile = EmployeeMobile.create! valid_attributes
      delete :destroy, {:id => employee_mobile.to_param}, valid_session
      response.should redirect_to(employee_mobiles_url)
    end
  end

end
