require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmployeeContactsController do

  # This should return the minimal set of attributes required to create a valid
  # EmployeeContact. As you add validations to EmployeeContact, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "extension" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmployeeContactsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all employee_contacts as @employee_contacts" do
      employee_contact = EmployeeContact.create! valid_attributes
      get :index, {}, valid_session
      assigns(:employee_contacts).should eq([employee_contact])
    end
  end

  describe "GET show" do
    it "assigns the requested employee_contact as @employee_contact" do
      employee_contact = EmployeeContact.create! valid_attributes
      get :show, {:id => employee_contact.to_param}, valid_session
      assigns(:employee_contact).should eq(employee_contact)
    end
  end

  describe "GET new" do
    it "assigns a new employee_contact as @employee_contact" do
      get :new, {}, valid_session
      assigns(:employee_contact).should be_a_new(EmployeeContact)
    end
  end

  describe "GET edit" do
    it "assigns the requested employee_contact as @employee_contact" do
      employee_contact = EmployeeContact.create! valid_attributes
      get :edit, {:id => employee_contact.to_param}, valid_session
      assigns(:employee_contact).should eq(employee_contact)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EmployeeContact" do
        expect {
          post :create, {:employee_contact => valid_attributes}, valid_session
        }.to change(EmployeeContact, :count).by(1)
      end

      it "assigns a newly created employee_contact as @employee_contact" do
        post :create, {:employee_contact => valid_attributes}, valid_session
        assigns(:employee_contact).should be_a(EmployeeContact)
        assigns(:employee_contact).should be_persisted
      end

      it "redirects to the created employee_contact" do
        post :create, {:employee_contact => valid_attributes}, valid_session
        response.should redirect_to(EmployeeContact.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved employee_contact as @employee_contact" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeContact.any_instance.stub(:save).and_return(false)
        post :create, {:employee_contact => { "extension" => "invalid value" }}, valid_session
        assigns(:employee_contact).should be_a_new(EmployeeContact)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeContact.any_instance.stub(:save).and_return(false)
        post :create, {:employee_contact => { "extension" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested employee_contact" do
        employee_contact = EmployeeContact.create! valid_attributes
        # Assuming there are no other employee_contacts in the database, this
        # specifies that the EmployeeContact created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EmployeeContact.any_instance.should_receive(:update).with({ "extension" => "MyString" })
        put :update, {:id => employee_contact.to_param, :employee_contact => { "extension" => "MyString" }}, valid_session
      end

      it "assigns the requested employee_contact as @employee_contact" do
        employee_contact = EmployeeContact.create! valid_attributes
        put :update, {:id => employee_contact.to_param, :employee_contact => valid_attributes}, valid_session
        assigns(:employee_contact).should eq(employee_contact)
      end

      it "redirects to the employee_contact" do
        employee_contact = EmployeeContact.create! valid_attributes
        put :update, {:id => employee_contact.to_param, :employee_contact => valid_attributes}, valid_session
        response.should redirect_to(employee_contact)
      end
    end

    describe "with invalid params" do
      it "assigns the employee_contact as @employee_contact" do
        employee_contact = EmployeeContact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeContact.any_instance.stub(:save).and_return(false)
        put :update, {:id => employee_contact.to_param, :employee_contact => { "extension" => "invalid value" }}, valid_session
        assigns(:employee_contact).should eq(employee_contact)
      end

      it "re-renders the 'edit' template" do
        employee_contact = EmployeeContact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeContact.any_instance.stub(:save).and_return(false)
        put :update, {:id => employee_contact.to_param, :employee_contact => { "extension" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested employee_contact" do
      employee_contact = EmployeeContact.create! valid_attributes
      expect {
        delete :destroy, {:id => employee_contact.to_param}, valid_session
      }.to change(EmployeeContact, :count).by(-1)
    end

    it "redirects to the employee_contacts list" do
      employee_contact = EmployeeContact.create! valid_attributes
      delete :destroy, {:id => employee_contact.to_param}, valid_session
      response.should redirect_to(employee_contacts_url)
    end
  end

end
