require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MobilesController do

  # This should return the minimal set of attributes required to create a valid
  # Mobile. As you add validations to Mobile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "number" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MobilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mobiles as @mobiles" do
      mobile = Mobile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mobiles).should eq([mobile])
    end
  end

  describe "GET show" do
    it "assigns the requested mobile as @mobile" do
      mobile = Mobile.create! valid_attributes
      get :show, {:id => mobile.to_param}, valid_session
      assigns(:mobile).should eq(mobile)
    end
  end

  describe "GET new" do
    it "assigns a new mobile as @mobile" do
      get :new, {}, valid_session
      assigns(:mobile).should be_a_new(Mobile)
    end
  end

  describe "GET edit" do
    it "assigns the requested mobile as @mobile" do
      mobile = Mobile.create! valid_attributes
      get :edit, {:id => mobile.to_param}, valid_session
      assigns(:mobile).should eq(mobile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mobile" do
        expect {
          post :create, {:mobile => valid_attributes}, valid_session
        }.to change(Mobile, :count).by(1)
      end

      it "assigns a newly created mobile as @mobile" do
        post :create, {:mobile => valid_attributes}, valid_session
        assigns(:mobile).should be_a(Mobile)
        assigns(:mobile).should be_persisted
      end

      it "redirects to the created mobile" do
        post :create, {:mobile => valid_attributes}, valid_session
        response.should redirect_to(Mobile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mobile as @mobile" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mobile.any_instance.stub(:save).and_return(false)
        post :create, {:mobile => { "number" => "invalid value" }}, valid_session
        assigns(:mobile).should be_a_new(Mobile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mobile.any_instance.stub(:save).and_return(false)
        post :create, {:mobile => { "number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mobile" do
        mobile = Mobile.create! valid_attributes
        # Assuming there are no other mobiles in the database, this
        # specifies that the Mobile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mobile.any_instance.should_receive(:update).with({ "number" => "MyString" })
        put :update, {:id => mobile.to_param, :mobile => { "number" => "MyString" }}, valid_session
      end

      it "assigns the requested mobile as @mobile" do
        mobile = Mobile.create! valid_attributes
        put :update, {:id => mobile.to_param, :mobile => valid_attributes}, valid_session
        assigns(:mobile).should eq(mobile)
      end

      it "redirects to the mobile" do
        mobile = Mobile.create! valid_attributes
        put :update, {:id => mobile.to_param, :mobile => valid_attributes}, valid_session
        response.should redirect_to(mobile)
      end
    end

    describe "with invalid params" do
      it "assigns the mobile as @mobile" do
        mobile = Mobile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mobile.any_instance.stub(:save).and_return(false)
        put :update, {:id => mobile.to_param, :mobile => { "number" => "invalid value" }}, valid_session
        assigns(:mobile).should eq(mobile)
      end

      it "re-renders the 'edit' template" do
        mobile = Mobile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mobile.any_instance.stub(:save).and_return(false)
        put :update, {:id => mobile.to_param, :mobile => { "number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mobile" do
      mobile = Mobile.create! valid_attributes
      expect {
        delete :destroy, {:id => mobile.to_param}, valid_session
      }.to change(Mobile, :count).by(-1)
    end

    it "redirects to the mobiles list" do
      mobile = Mobile.create! valid_attributes
      delete :destroy, {:id => mobile.to_param}, valid_session
      response.should redirect_to(mobiles_url)
    end
  end

end
