require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NonBuildingsController do

  # This should return the minimal set of attributes required to create a valid
  # NonBuilding. As you add validations to NonBuilding, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NonBuildingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all non_buildings as @non_buildings" do
      non_building = NonBuilding.create! valid_attributes
      get :index, {}, valid_session
      assigns(:non_buildings).should eq([non_building])
    end
  end

  describe "GET show" do
    it "assigns the requested config_project as @config_project" do
      non_building = NonBuilding.create! valid_attributes
      get :show, {:id => non_building.to_param}, valid_session
      assigns(:config_project).should eq(non_building)
    end
  end

  describe "GET new" do
    it "assigns a new config_project as @config_project" do
      get :new, {}, valid_session
      assigns(:config_project).should be_a_new(NonBuilding)
    end
  end

  describe "GET edit" do
    it "assigns the requested config_project as @config_project" do
      non_building = NonBuilding.create! valid_attributes
      get :edit, {:id => non_building.to_param}, valid_session
      assigns(:config_project).should eq(non_building)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NonBuilding" do
        expect {
          post :create, {:config_project => valid_attributes}, valid_session
        }.to change(NonBuilding, :count).by(1)
      end

      it "assigns a newly created config_project as @config_project" do
        post :create, {:config_project => valid_attributes}, valid_session
        assigns(:config_project).should be_a(NonBuilding)
        assigns(:config_project).should be_persisted
      end

      it "redirects to the created config_project" do
        post :create, {:config_project => valid_attributes}, valid_session
        response.should redirect_to(NonBuilding.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved config_project as @config_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        NonBuilding.any_instance.stub(:save).and_return(false)
        post :create, {:config_project => { "name" => "invalid value" }}, valid_session
        assigns(:config_project).should be_a_new(NonBuilding)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NonBuilding.any_instance.stub(:save).and_return(false)
        post :create, {:config_project => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested config_project" do
        non_building = NonBuilding.create! valid_attributes
        # Assuming there are no other non_buildings in the database, this
        # specifies that the NonBuilding created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NonBuilding.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => non_building.to_param, :config_project => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested config_project as @config_project" do
        non_building = NonBuilding.create! valid_attributes
        put :update, {:id => non_building.to_param, :config_project => valid_attributes}, valid_session
        assigns(:config_project).should eq(non_building)
      end

      it "redirects to the config_project" do
        non_building = NonBuilding.create! valid_attributes
        put :update, {:id => non_building.to_param, :config_project => valid_attributes}, valid_session
        response.should redirect_to(non_building)
      end
    end

    describe "with invalid params" do
      it "assigns the config_project as @config_project" do
        non_building = NonBuilding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NonBuilding.any_instance.stub(:save).and_return(false)
        put :update, {:id => non_building.to_param, :config_project => { "name" => "invalid value" }}, valid_session
        assigns(:config_project).should eq(non_building)
      end

      it "re-renders the 'edit' template" do
        non_building = NonBuilding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NonBuilding.any_instance.stub(:save).and_return(false)
        put :update, {:id => non_building.to_param, :config_project => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested config_project" do
      non_building = NonBuilding.create! valid_attributes
      expect {
        delete :destroy, {:id => non_building.to_param}, valid_session
      }.to change(NonBuilding, :count).by(-1)
    end

    it "redirects to the non_buildings list" do
      non_building = NonBuilding.create! valid_attributes
      delete :destroy, {:id => non_building.to_param}, valid_session
      response.should redirect_to(non_buildings_url)
    end
  end

end
