require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OfficeCulturesController do

  # This should return the minimal set of attributes required to create a valid
  # OfficeCulture. As you add validations to OfficeCulture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "first_aider" => "false" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OfficeCulturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all office_cultures as @office_cultures" do
      office_culture = OfficeCulture.create! valid_attributes
      get :index, {}, valid_session
      assigns(:office_cultures).should eq([office_culture])
    end
  end

  describe "GET show" do
    it "assigns the requested config_model as @config_model" do
      office_culture = OfficeCulture.create! valid_attributes
      get :show, {:id => office_culture.to_param}, valid_session
      assigns(:config_model).should eq(office_culture)
    end
  end

  describe "GET new" do
    it "assigns a new config_model as @config_model" do
      get :new, {}, valid_session
      assigns(:config_model).should be_a_new(OfficeCulture)
    end
  end

  describe "GET edit" do
    it "assigns the requested config_model as @config_model" do
      office_culture = OfficeCulture.create! valid_attributes
      get :edit, {:id => office_culture.to_param}, valid_session
      assigns(:config_model).should eq(office_culture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OfficeCulture" do
        expect {
          post :create, {:config_model => valid_attributes}, valid_session
        }.to change(OfficeCulture, :count).by(1)
      end

      it "assigns a newly created config_model as @config_model" do
        post :create, {:config_model => valid_attributes}, valid_session
        assigns(:config_model).should be_a(OfficeCulture)
        assigns(:config_model).should be_persisted
      end

      it "redirects to the created config_model" do
        post :create, {:config_model => valid_attributes}, valid_session
        response.should redirect_to(OfficeCulture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved config_model as @config_model" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeCulture.any_instance.stub(:save).and_return(false)
        post :create, {:config_model => { "first_aider" => "invalid value" }}, valid_session
        assigns(:config_model).should be_a_new(OfficeCulture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeCulture.any_instance.stub(:save).and_return(false)
        post :create, {:config_model => { "first_aider" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested config_model" do
        office_culture = OfficeCulture.create! valid_attributes
        # Assuming there are no other office_cultures in the database, this
        # specifies that the OfficeCulture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OfficeCulture.any_instance.should_receive(:update).with({ "first_aider" => "false" })
        put :update, {:id => office_culture.to_param, :config_model => { "first_aider" => "false" }}, valid_session
      end

      it "assigns the requested config_model as @config_model" do
        office_culture = OfficeCulture.create! valid_attributes
        put :update, {:id => office_culture.to_param, :config_model => valid_attributes}, valid_session
        assigns(:config_model).should eq(office_culture)
      end

      it "redirects to the config_model" do
        office_culture = OfficeCulture.create! valid_attributes
        put :update, {:id => office_culture.to_param, :config_model => valid_attributes}, valid_session
        response.should redirect_to(office_culture)
      end
    end

    describe "with invalid params" do
      it "assigns the config_model as @config_model" do
        office_culture = OfficeCulture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeCulture.any_instance.stub(:save).and_return(false)
        put :update, {:id => office_culture.to_param, :config_model => { "first_aider" => "invalid value" }}, valid_session
        assigns(:config_model).should eq(office_culture)
      end

      it "re-renders the 'edit' template" do
        office_culture = OfficeCulture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeCulture.any_instance.stub(:save).and_return(false)
        put :update, {:id => office_culture.to_param, :config_model => { "first_aider" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested config_model" do
      office_culture = OfficeCulture.create! valid_attributes
      expect {
        delete :destroy, {:id => office_culture.to_param}, valid_session
      }.to change(OfficeCulture, :count).by(-1)
    end

    it "redirects to the office_cultures list" do
      office_culture = OfficeCulture.create! valid_attributes
      delete :destroy, {:id => office_culture.to_param}, valid_session
      response.should redirect_to(office_cultures_url)
    end
  end

end
