require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PassportsController do

  # This should return the minimal set of attributes required to create a valid
  # Passport. As you add validations to Passport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "number" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PassportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all passports as @passports" do
      passport = Passport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:passports).should eq([passport])
    end
  end

  describe "GET show" do
    it "assigns the requested passport as @passport" do
      passport = Passport.create! valid_attributes
      get :show, {:id => passport.to_param}, valid_session
      assigns(:passport).should eq(passport)
    end
  end

  describe "GET new" do
    it "assigns a new passport as @passport" do
      get :new, {}, valid_session
      assigns(:passport).should be_a_new(Passport)
    end
  end

  describe "GET edit" do
    it "assigns the requested passport as @passport" do
      passport = Passport.create! valid_attributes
      get :edit, {:id => passport.to_param}, valid_session
      assigns(:passport).should eq(passport)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Passport" do
        expect {
          post :create, {:passport => valid_attributes}, valid_session
        }.to change(Passport, :count).by(1)
      end

      it "assigns a newly created passport as @passport" do
        post :create, {:passport => valid_attributes}, valid_session
        assigns(:passport).should be_a(Passport)
        assigns(:passport).should be_persisted
      end

      it "redirects to the created passport" do
        post :create, {:passport => valid_attributes}, valid_session
        response.should redirect_to(Passport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved passport as @passport" do
        # Trigger the behavior that occurs when invalid params are submitted
        Passport.any_instance.stub(:save).and_return(false)
        post :create, {:passport => { "number" => "invalid value" }}, valid_session
        assigns(:passport).should be_a_new(Passport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Passport.any_instance.stub(:save).and_return(false)
        post :create, {:passport => { "number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested passport" do
        passport = Passport.create! valid_attributes
        # Assuming there are no other passports in the database, this
        # specifies that the Passport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Passport.any_instance.should_receive(:update).with({ "number" => "MyString" })
        put :update, {:id => passport.to_param, :passport => { "number" => "MyString" }}, valid_session
      end

      it "assigns the requested passport as @passport" do
        passport = Passport.create! valid_attributes
        put :update, {:id => passport.to_param, :passport => valid_attributes}, valid_session
        assigns(:passport).should eq(passport)
      end

      it "redirects to the passport" do
        passport = Passport.create! valid_attributes
        put :update, {:id => passport.to_param, :passport => valid_attributes}, valid_session
        response.should redirect_to(passport)
      end
    end

    describe "with invalid params" do
      it "assigns the passport as @passport" do
        passport = Passport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Passport.any_instance.stub(:save).and_return(false)
        put :update, {:id => passport.to_param, :passport => { "number" => "invalid value" }}, valid_session
        assigns(:passport).should eq(passport)
      end

      it "re-renders the 'edit' template" do
        passport = Passport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Passport.any_instance.stub(:save).and_return(false)
        put :update, {:id => passport.to_param, :passport => { "number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested passport" do
      passport = Passport.create! valid_attributes
      expect {
        delete :destroy, {:id => passport.to_param}, valid_session
      }.to change(Passport, :count).by(-1)
    end

    it "redirects to the passports list" do
      passport = Passport.create! valid_attributes
      delete :destroy, {:id => passport.to_param}, valid_session
      response.should redirect_to(passports_url)
    end
  end

end
