require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PersonNamesController do

  # This should return the minimal set of attributes required to create a valid
  # PersonName. As you add validations to PersonName, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "prefix" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PersonNamesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all person_names as @person_names" do
      person_name = PersonName.create! valid_attributes
      get :index, {}, valid_session
      assigns(:person_names).should eq([person_name])
    end
  end

  describe "GET show" do
    it "assigns the requested person_name as @person_name" do
      person_name = PersonName.create! valid_attributes
      get :show, {:id => person_name.to_param}, valid_session
      assigns(:person_name).should eq(person_name)
    end
  end

  describe "GET new" do
    it "assigns a new person_name as @person_name" do
      get :new, {}, valid_session
      assigns(:person_name).should be_a_new(PersonName)
    end
  end

  describe "GET edit" do
    it "assigns the requested person_name as @person_name" do
      person_name = PersonName.create! valid_attributes
      get :edit, {:id => person_name.to_param}, valid_session
      assigns(:person_name).should eq(person_name)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PersonName" do
        expect {
          post :create, {:person_name => valid_attributes}, valid_session
        }.to change(PersonName, :count).by(1)
      end

      it "assigns a newly created person_name as @person_name" do
        post :create, {:person_name => valid_attributes}, valid_session
        assigns(:person_name).should be_a(PersonName)
        assigns(:person_name).should be_persisted
      end

      it "redirects to the created person_name" do
        post :create, {:person_name => valid_attributes}, valid_session
        response.should redirect_to(PersonName.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved person_name as @person_name" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonName.any_instance.stub(:save).and_return(false)
        post :create, {:person_name => { "prefix" => "invalid value" }}, valid_session
        assigns(:person_name).should be_a_new(PersonName)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonName.any_instance.stub(:save).and_return(false)
        post :create, {:person_name => { "prefix" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested person_name" do
        person_name = PersonName.create! valid_attributes
        # Assuming there are no other person_names in the database, this
        # specifies that the PersonName created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PersonName.any_instance.should_receive(:update).with({ "prefix" => "MyString" })
        put :update, {:id => person_name.to_param, :person_name => { "prefix" => "MyString" }}, valid_session
      end

      it "assigns the requested person_name as @person_name" do
        person_name = PersonName.create! valid_attributes
        put :update, {:id => person_name.to_param, :person_name => valid_attributes}, valid_session
        assigns(:person_name).should eq(person_name)
      end

      it "redirects to the person_name" do
        person_name = PersonName.create! valid_attributes
        put :update, {:id => person_name.to_param, :person_name => valid_attributes}, valid_session
        response.should redirect_to(person_name)
      end
    end

    describe "with invalid params" do
      it "assigns the person_name as @person_name" do
        person_name = PersonName.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonName.any_instance.stub(:save).and_return(false)
        put :update, {:id => person_name.to_param, :person_name => { "prefix" => "invalid value" }}, valid_session
        assigns(:person_name).should eq(person_name)
      end

      it "re-renders the 'edit' template" do
        person_name = PersonName.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonName.any_instance.stub(:save).and_return(false)
        put :update, {:id => person_name.to_param, :person_name => { "prefix" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested person_name" do
      person_name = PersonName.create! valid_attributes
      expect {
        delete :destroy, {:id => person_name.to_param}, valid_session
      }.to change(PersonName, :count).by(-1)
    end

    it "redirects to the person_names list" do
      person_name = PersonName.create! valid_attributes
      delete :destroy, {:id => person_name.to_param}, valid_session
      response.should redirect_to(person_names_url)
    end
  end

end
