require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProfessionalContributionsController do

  # This should return the minimal set of attributes required to create a valid
  # ProfessionalContribution. As you add validations to ProfessionalContribution, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "activity" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProfessionalContributionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all professional_contributions as @professional_contributions" do
      professional_contribution = ProfessionalContribution.create! valid_attributes
      get :index, {}, valid_session
      assigns(:professional_contributions).should eq([professional_contribution])
    end
  end

  describe "GET show" do
    it "assigns the requested professional_contribution as @professional_contribution" do
      professional_contribution = ProfessionalContribution.create! valid_attributes
      get :show, {:id => professional_contribution.to_param}, valid_session
      assigns(:professional_contribution).should eq(professional_contribution)
    end
  end

  describe "GET new" do
    it "assigns a new professional_contribution as @professional_contribution" do
      get :new, {}, valid_session
      assigns(:professional_contribution).should be_a_new(ProfessionalContribution)
    end
  end

  describe "GET edit" do
    it "assigns the requested professional_contribution as @professional_contribution" do
      professional_contribution = ProfessionalContribution.create! valid_attributes
      get :edit, {:id => professional_contribution.to_param}, valid_session
      assigns(:professional_contribution).should eq(professional_contribution)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProfessionalContribution" do
        expect {
          post :create, {:professional_contribution => valid_attributes}, valid_session
        }.to change(ProfessionalContribution, :count).by(1)
      end

      it "assigns a newly created professional_contribution as @professional_contribution" do
        post :create, {:professional_contribution => valid_attributes}, valid_session
        assigns(:professional_contribution).should be_a(ProfessionalContribution)
        assigns(:professional_contribution).should be_persisted
      end

      it "redirects to the created professional_contribution" do
        post :create, {:professional_contribution => valid_attributes}, valid_session
        response.should redirect_to(ProfessionalContribution.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved professional_contribution as @professional_contribution" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProfessionalContribution.any_instance.stub(:save).and_return(false)
        post :create, {:professional_contribution => { "activity" => "invalid value" }}, valid_session
        assigns(:professional_contribution).should be_a_new(ProfessionalContribution)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProfessionalContribution.any_instance.stub(:save).and_return(false)
        post :create, {:professional_contribution => { "activity" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested professional_contribution" do
        professional_contribution = ProfessionalContribution.create! valid_attributes
        # Assuming there are no other professional_contributions in the database, this
        # specifies that the ProfessionalContribution created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProfessionalContribution.any_instance.should_receive(:update).with({ "activity" => "MyString" })
        put :update, {:id => professional_contribution.to_param, :professional_contribution => { "activity" => "MyString" }}, valid_session
      end

      it "assigns the requested professional_contribution as @professional_contribution" do
        professional_contribution = ProfessionalContribution.create! valid_attributes
        put :update, {:id => professional_contribution.to_param, :professional_contribution => valid_attributes}, valid_session
        assigns(:professional_contribution).should eq(professional_contribution)
      end

      it "redirects to the professional_contribution" do
        professional_contribution = ProfessionalContribution.create! valid_attributes
        put :update, {:id => professional_contribution.to_param, :professional_contribution => valid_attributes}, valid_session
        response.should redirect_to(professional_contribution)
      end
    end

    describe "with invalid params" do
      it "assigns the professional_contribution as @professional_contribution" do
        professional_contribution = ProfessionalContribution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProfessionalContribution.any_instance.stub(:save).and_return(false)
        put :update, {:id => professional_contribution.to_param, :professional_contribution => { "activity" => "invalid value" }}, valid_session
        assigns(:professional_contribution).should eq(professional_contribution)
      end

      it "re-renders the 'edit' template" do
        professional_contribution = ProfessionalContribution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProfessionalContribution.any_instance.stub(:save).and_return(false)
        put :update, {:id => professional_contribution.to_param, :professional_contribution => { "activity" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested professional_contribution" do
      professional_contribution = ProfessionalContribution.create! valid_attributes
      expect {
        delete :destroy, {:id => professional_contribution.to_param}, valid_session
      }.to change(ProfessionalContribution, :count).by(-1)
    end

    it "redirects to the professional_contributions list" do
      professional_contribution = ProfessionalContribution.create! valid_attributes
      delete :destroy, {:id => professional_contribution.to_param}, valid_session
      response.should redirect_to(professional_contributions_url)
    end
  end

end
