require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QualificationsController do

  # This should return the minimal set of attributes required to create a valid
  # Qualification. As you add validations to Qualification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QualificationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all qualifications as @qualifications" do
      qualification = Qualification.create! valid_attributes
      get :index, {}, valid_session
      assigns(:qualifications).should eq([qualification])
    end
  end

  describe "GET show" do
    it "assigns the requested config_person as @config_person" do
      qualification = Qualification.create! valid_attributes
      get :show, {:id => qualification.to_param}, valid_session
      assigns(:config_person).should eq(qualification)
    end
  end

  describe "GET new" do
    it "assigns a new config_person as @config_person" do
      get :new, {}, valid_session
      assigns(:config_person).should be_a_new(Qualification)
    end
  end

  describe "GET edit" do
    it "assigns the requested config_person as @config_person" do
      qualification = Qualification.create! valid_attributes
      get :edit, {:id => qualification.to_param}, valid_session
      assigns(:config_person).should eq(qualification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Qualification" do
        expect {
          post :create, {:config_person => valid_attributes}, valid_session
        }.to change(Qualification, :count).by(1)
      end

      it "assigns a newly created config_person as @config_person" do
        post :create, {:config_person => valid_attributes}, valid_session
        assigns(:config_person).should be_a(Qualification)
        assigns(:config_person).should be_persisted
      end

      it "redirects to the created config_person" do
        post :create, {:config_person => valid_attributes}, valid_session
        response.should redirect_to(Qualification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved config_person as @config_person" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualification.any_instance.stub(:save).and_return(false)
        post :create, {:config_person => { "name" => "invalid value" }}, valid_session
        assigns(:config_person).should be_a_new(Qualification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualification.any_instance.stub(:save).and_return(false)
        post :create, {:config_person => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested config_person" do
        qualification = Qualification.create! valid_attributes
        # Assuming there are no other qualifications in the database, this
        # specifies that the Qualification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Qualification.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => qualification.to_param, :config_person => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested config_person as @config_person" do
        qualification = Qualification.create! valid_attributes
        put :update, {:id => qualification.to_param, :config_person => valid_attributes}, valid_session
        assigns(:config_person).should eq(qualification)
      end

      it "redirects to the config_person" do
        qualification = Qualification.create! valid_attributes
        put :update, {:id => qualification.to_param, :config_person => valid_attributes}, valid_session
        response.should redirect_to(qualification)
      end
    end

    describe "with invalid params" do
      it "assigns the config_person as @config_person" do
        qualification = Qualification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualification.any_instance.stub(:save).and_return(false)
        put :update, {:id => qualification.to_param, :config_person => { "name" => "invalid value" }}, valid_session
        assigns(:config_person).should eq(qualification)
      end

      it "re-renders the 'edit' template" do
        qualification = Qualification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualification.any_instance.stub(:save).and_return(false)
        put :update, {:id => qualification.to_param, :config_person => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested config_person" do
      qualification = Qualification.create! valid_attributes
      expect {
        delete :destroy, {:id => qualification.to_param}, valid_session
      }.to change(Qualification, :count).by(-1)
    end

    it "redirects to the qualifications list" do
      qualification = Qualification.create! valid_attributes
      delete :destroy, {:id => qualification.to_param}, valid_session
      response.should redirect_to(qualifications_url)
    end
  end

end
