require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SecurityClearancesController do

  # This should return the minimal set of attributes required to create a valid
  # SecurityClearance. As you add validations to SecurityClearance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "issuing_body" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SecurityClearancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all security_clearances as @security_clearances" do
      security_clearance = SecurityClearance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:security_clearances).should eq([security_clearance])
    end
  end

  describe "GET show" do
    it "assigns the requested config_person as @config_person" do
      security_clearance = SecurityClearance.create! valid_attributes
      get :show, {:id => security_clearance.to_param}, valid_session
      assigns(:config_person).should eq(security_clearance)
    end
  end

  describe "GET new" do
    it "assigns a new config_person as @config_person" do
      get :new, {}, valid_session
      assigns(:config_person).should be_a_new(SecurityClearance)
    end
  end

  describe "GET edit" do
    it "assigns the requested config_person as @config_person" do
      security_clearance = SecurityClearance.create! valid_attributes
      get :edit, {:id => security_clearance.to_param}, valid_session
      assigns(:config_person).should eq(security_clearance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SecurityClearance" do
        expect {
          post :create, {:config_person => valid_attributes}, valid_session
        }.to change(SecurityClearance, :count).by(1)
      end

      it "assigns a newly created config_person as @config_person" do
        post :create, {:config_person => valid_attributes}, valid_session
        assigns(:config_person).should be_a(SecurityClearance)
        assigns(:config_person).should be_persisted
      end

      it "redirects to the created config_person" do
        post :create, {:config_person => valid_attributes}, valid_session
        response.should redirect_to(SecurityClearance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved config_person as @config_person" do
        # Trigger the behavior that occurs when invalid params are submitted
        SecurityClearance.any_instance.stub(:save).and_return(false)
        post :create, {:config_person => { "issuing_body" => "invalid value" }}, valid_session
        assigns(:config_person).should be_a_new(SecurityClearance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SecurityClearance.any_instance.stub(:save).and_return(false)
        post :create, {:config_person => { "issuing_body" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested config_person" do
        security_clearance = SecurityClearance.create! valid_attributes
        # Assuming there are no other security_clearances in the database, this
        # specifies that the SecurityClearance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SecurityClearance.any_instance.should_receive(:update).with({ "issuing_body" => "MyString" })
        put :update, {:id => security_clearance.to_param, :config_person => { "issuing_body" => "MyString" }}, valid_session
      end

      it "assigns the requested config_person as @config_person" do
        security_clearance = SecurityClearance.create! valid_attributes
        put :update, {:id => security_clearance.to_param, :config_person => valid_attributes}, valid_session
        assigns(:config_person).should eq(security_clearance)
      end

      it "redirects to the config_person" do
        security_clearance = SecurityClearance.create! valid_attributes
        put :update, {:id => security_clearance.to_param, :config_person => valid_attributes}, valid_session
        response.should redirect_to(security_clearance)
      end
    end

    describe "with invalid params" do
      it "assigns the config_person as @config_person" do
        security_clearance = SecurityClearance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SecurityClearance.any_instance.stub(:save).and_return(false)
        put :update, {:id => security_clearance.to_param, :config_person => { "issuing_body" => "invalid value" }}, valid_session
        assigns(:config_person).should eq(security_clearance)
      end

      it "re-renders the 'edit' template" do
        security_clearance = SecurityClearance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SecurityClearance.any_instance.stub(:save).and_return(false)
        put :update, {:id => security_clearance.to_param, :config_person => { "issuing_body" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested config_person" do
      security_clearance = SecurityClearance.create! valid_attributes
      expect {
        delete :destroy, {:id => security_clearance.to_param}, valid_session
      }.to change(SecurityClearance, :count).by(-1)
    end

    it "redirects to the security_clearances list" do
      security_clearance = SecurityClearance.create! valid_attributes
      delete :destroy, {:id => security_clearance.to_param}, valid_session
      response.should redirect_to(security_clearances_url)
    end
  end

end
