source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'mongoid', github: 'mongoid/mongoid'
gem 'bson_ext'

gem 'factory_girl_rails', '~> 4.0'#, group: [:test, :development]
gem 'faker'#, group: [:test, :development]
gem 'rspec-rails', group: [:test, :development]
group :test do
  gem 'guard-rspec'
  gem 'mongoid-rspec', github: 'evansagge/mongoid-rspec'
end

group :assets do
  gem 'uglifier'
  gem 'sass-rails'
end

gem 'rack-cors', :require => 'rack/cors'

gem 'mongoid-model-maker', github: 'Dawil/MongoidModelMaker'

gem 'devise'
gem 'omniauth'
gem 'omniauth-ldap', github: 'Dawil/omniauth-ldap'
